smicallef/spiderfoot

- dyn/HEADER.tmpl
- dyn/newscan.tmpl
- dyn/opts.tmpl
- dyn/scandelete.tmpl
- dyn/scaninfo.tmpl
- dyn/scanlist.tmpl
- sf.py
- sfwebui.py
So it's possible to use a reverse proxy with SpiderFoot running in a docker image.
> Add path prefix

- Dockerfile
- Runs application using a dedicated/non-privileged user (spiderfoot).
- Adheres to published Docker best-practices.
> Adds Dockerfile to simplify deployment.

- modules/sfp_mnemonic.py
> Add sfp_mnemonic module

- modules/sfp_flickr.py
> Add Flickr module

- modules/sfp_github.py
Update sfp_github module to watch for `SOCIAL_MEDIA` events and extract name and location from profiles.
> Update sfp_github to extract name and location from profiles

- modules/sfp_slideshare.py
Add sfp_slideshare module.
Transforms SlideShare `SOCIAL_MEDIA` event to `HUMAN_NAME` and potentially `GEOINFO` (country).
> Add sfp_slideshare module

- modules/sfp_bingsharedip.py
- modules/sfp_circllu.py
- modules/sfp_hackertarget.py
- modules/sfp_mnemonic.py
- modules/sfp_riskiq.py
- modules/sfp_robtex.py
- modules/sfp_securitytrails.py
- modules/sfp_viewdns.py
Print host and IP when host no longer resolves to IP.
Untested.
> Print host and IP when host no longer resolves to IP

- modules/sfp_hackertarget.py
Reports `TCP_PORT_OPEN` and `UDP_PORT_OPEN` in the form of `ip:port`.
This is due to the event type potentially being a netblock. Presumably, simply reporting `port` would not indicate which ip had the port open.
> Add TCP/UDP port scan to sfp_hackertarget module

- modules/sfp_webanalytics.py
https://github.com/smicallef/spiderfoot/pull/218#discussion_r228707146
> Add sfp_webanalytics

- modules/sf_h1nobbdde.py
Added support for `sfp_h1nobbdde` which query the [unofficial HackerOne ](http://h1.nobbd.de/)disclosure timeline database  to see if our target appears.
> Add sfp_h1nobbdde

- modules/sfp_citadel.py
Site has changed domain and they have re-written their API.
I've tested everything below, but you may want to give it a run through before pushing live.
Public API key is now limited to 1,500 searches a day to stop to much overhead.
https://leak-lookup.com/api
> sfp_citadel.py changes.

- dyn/scanlist.tmpl
- sfwebui.py
Add support for JSON exports. Supports exporting one or multiple scans.
For consistency, the primary JSON key for each scan is `scan_name`, which is effectively the source data provided via the UI to start the scan. This is in line with the `Scan Name` as used in the CSV exporting functionality.
Example JSON output for two scans:
```json
{
"123.123.123.124": [
{
"source_module": "sfp_hackertarget",
"data": "123.123.123.123.redacted.local",
"source_data": "123.123.123.124",
"false_positive": 0,
"lastseen": "2019-03-04 16:03:34",
"type": "CO_HOSTED_SITE"
},
{
"source_module": "SpiderFoot UI",
"data": "123.123.123.124",
"source_data": "123.123.123.124",
"false_positive": 0,
"lastseen": "2019-03-04 16:03:34",
"type": "IP_ADDRESS"
},
{
"source_module": "sfp_hackertarget",
"data": …
```
> Add support for JSON exports

- modules/sfp_numverify.py
Depends on #274 to add `PROVIDER_TELCO` data type.
> Add sfp_numverify module

- modules/sfp_neutrinoapi.py
Add phone number lookup to sfp_neutrinoapi module.
Also ninja patches an issues where attempts to store `RAW_RIR_DATA` were failing due to attempting to store the API response `data` as a `dict` rather than a `str`.
> Add phone number lookup to sfp_neutrinoapi module

- modules/sfp_phone.py
Utilises Google's `libphonenumber` ([python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers)) to return `PROVIDER_TELCO` for a specified phone number.
Code for returning the location has also been added, commented out, as [the geocoder has significant memory overhead](https://github.com/daviddrysdale/python-phonenumbers#memory-usage).
> Return PROVIDER_TELCO with carrier.name_for_number

- sfwebui.py
Compare before and after the PR with URL:
* http://127.0.0.1:5001/scaninfo?id[]
> Add 404 error page

- modules/sfp__stor_stdout.py
- modules/sfp_alienvault.py
- modules/sfp_censys.py
- modules/sfp_fraudguard.py
- modules/sfp_greynoise.py
- modules/sfp_pulsedive.py
- sf.py
- sfcli.py
- sfdb.py
- sflib.py
- sfscan.py
- sfwebui.py
https://python-future.org/compatible_idioms.html#print
These changes should be identical, with one minor exception in `sfcli.py`:
```diff
-        print "\n",
+        print("\n")
return True
```
> Use Python 3 print style

- modules/sfp_darksearch.py
I haven't tested this, but it should fix #301
> Quote search query

- modules/sfp_s3bucket.py
Based on what I found and other reports, I add some s3 suffix like prod, production, staging, etc
> Add bucket suffixes

- modules/sfp_webanalytics.py
Also eliminates some potential false positive matches for generic / placeholder IDs.
> Add Google AdSense to sfp_webanalytics

- modules/sfp_ssltools.py
Largely copied from `sfp_sslcert` module.
> Add sfp_ssltools

- modules/sfp_sslcert.py
Depends on #326 to add `AFFILIATE_DOMAIN_UNRESOLVED` entity data type.
> Add extraction for cert SANs

- modules/sfp_webanalytics.py
Add matches to `sfp_webanalytics` module. Mostly matches for `DNS` `TXT` records.
Also changes events to be reported with `parentEvent` rather than `event`, which seemed like a good idea.
> Add matches to sfp_webanalytics

- modules/sfp_instagram.py
Returns profile data as `RAW_RIR_DATA`.
Relies on parsing modules `sfp_names` and `sfp_email` to pull interesting info out of the profile JSON data.
> Add sfp_instagram

- modules/sfp_webanalytics.py
Add reference URLs to `sfp_webanalytics`.
Also adds Stripe domain verification, adds TeamViewer SSO verification, and fixes a typo with Drift domain verification.
> Add reference URLs to sfp_webanalytics

- modules/sfp_ipinfo.py
Update `sfp_ipinfo`.
* Add `IPV6_ADDRESS` to watched events
* Replaces `results` `dict()` with `self.tempStorage()`
* Change authentication from `token` HTTP parameter to `Authorization` HTTP header
* set `errorState = True` when rate-limited (rate limits are set on a per-month basis)
* Move query functionality to a `queryIP` method
* Normalize `GEOIP` output similar to other modules (join on `, `, and drop null city/region)
> Update sfp_ipinfo module

- modules/sfp_censys.py
Update `sfp_censys`.
* Adds a `delay` option, to prevent exceeding the rate limit.
* Replaces `results` `dict()` with `self.tempStorage()`
* Stores `RAW_RIR_DATA`
* Syntax and style cleanup. In particular, `if rec is None: continue` inside the loop.
* Bug fix: `if 'error' in rec and 'error_type' == "unknown":` now checks `rec['error_type']`.
There's more to be done for this module, but I'll leave that until after this PR is merged. Specifically:
* parsing certificate SANs
* Fixing the HTTP header parsing. Currently this does not work, as the `headers` key is only present within each port key.
> Update sfp_censys module

- modules/sfp_scylla.py
Replace 0377b1beafb6e55fe22d51bebb48d8a7f4c33d30
> Filter out false positives and prevent duplicates

- modules/sfp_bingsearch.py
- modules/sfp_bingsharedip.py
- modules/sfp_googlesearch.py
- modules/sfp_googlesearchdomain.py
- modules/sfp_onioncity.py
- modules/sfp_pastebin.py
- modules/sfp_socialprofiles.py
- sflib.py
- refactor: use clearer variable names and remove unnecessary conditions
> WIP: Add bing & Google API

- modules/sfp_darksearch.py
- modules/sfp_dnsneighbor.py
- modules/sfp_flickr.py
- modules/sfp_intelx.py
- modules/sfp_onionsearchengine.py
- modules/sfp_scylla.py
- modules/sfp_torch.py
Adds `self.checkForStop()` to most module loops. Seems like a good idea. I skipped a few modules which use threading.
> Use self.checkForStop() in module loops

- modules/sfp_webanalytics.py
Add analytics IDs to `sfp_webanalytics`.
> Add analytics IDs

- modules/sfp_crt.py
* Use `json` library for parsing JSON data, rather than regex
* Use `urllib` to encode paramaters
* Query using `q` rather than `CN`
* Store subject alternative names
> Cleanup sfp_crt

- sflib.py
> Use sflib.resolveHost in sflib.checkDnsWildcard function

- modules/sfp_ssltools.py
* Use `urllib` and `raw_unicode_escape` encoding for consistency with other modules.
* Rename `hdr` variable to `headers` for consistency with other modules.
> Use urllib for consistency

- modules/sfp_hunter.py
Comment out debug code. Looks like these were left in after debugging (?).
Also changes the `print` function calls to use Python3 style.
> Comment out debug code

- requirements.txt
- sflib.py
- sfwebui.py
- fix csv export
- fix json export
- fix gexf exporting
- fix importing exported API keys
> Fix Exporting & Importing files in Py3

- sflib.py
- tests/test_sflib.py
Dependencies are `pytest` and `pytest-mock`, how should test requirements be added? a separate `requirements-test.txt` file?
> Py3 - Initial tests

- .gitignore
- requirements_test.txt
- sflib.py
- test/unit/conftest.py
- test/unit/test_sflib.py
Note: I have marked some questions with 'TODO', will remove these comments once we address them.
> Improve Python 3 Test Suite

- modules/sfp_hackertarget.py
> Fix undefined name: 'name' --> 'eventData'

- sfwebui.py
Provide useful error messages which are slightly more descriptive than `Form incomplete`.
This also helps narrow down the cause of an issue to a specific conditional branch when debugging.
Also switch the conditional branch logic such that the True branch is first.
> sfwebui: Provide intuitive error messages

- modules/sfp_open_passive_dns_database.py
Add sfp_open_passive_dns_database module.
```
Obtain passive DNS information from pdns.daloo.de Open passive DNS database.
```
```python
def watchedEvents(self):
return ["DOMAIN_NAME"]
def producedEvents(self):
return ["INTERNET_NAME", "INTERNET_NAME_UNRESOLVED", "IP_ADDRESS", "IPV6_ADDRESS"]
```
> Add sfp_open_passive_dns_database

- modules/sfp_networksdb.py
SpiderFoot plug-in to search [NetworksDB.io API](https://networksdb.io/api/docs) for IP address and domain information.
```python
def watchedEvents(self):
return ["IP_ADDRESS", "IPV6_ADDRESS", "INTERNET_NAME", "DOMAIN_NAME"]
def producedEvents(self):
return ["INTERNET_NAME", "IP_ADDRESS", "IPV6_ADDRESS", "NETBLOCK_MEMBER",
"CO_HOSTED_SITE", "GEOINFO", "RAW_RIR_DATA"]
```
> Add sfp_networksdb

- modules/sfp_spyse.py
Note: pagination is not implemented. Only the first page of results are returned from each API endpoint.
> Add sfp_spyse

- modules/sfp_creditcard.py
- modules/sfp_email.py
- sfdb.py
- sflib.py
**Implemented sf_creditcard.py module**
**Changes:** 
- Developed sf_creditcard.py
- Implemented parseCreditCard(self,data) in sflib.py
- Added entry for "CREDIT_CARD_NUMBER" in sfdb.py
**Functionality:** 
Extract credit card information from the incoming "TARGET_WEB_CONTENT" data source.
> Implemented sf_creditcard.py

- modules/sfp_countryname.py
Adding a few bug fixes, additional checks
> Changes in sfp_countryname.py

- modules/sfp_grep_app.py
Requires `sf.extractUrls()` function, currently pending merge in #507
> Add sfp_grep_app

- modules/sfp_flickr.py
Requires `sf.extractUrls()` function, currently pending merge in #507
> Update sfp_flickr to extract URLs and domains

- modules/sfp_badpackets.py
Implementing malicious IP address detection & data extraction using Bad Packets API
> Implement sfp_badpackets module

- modules/sfp_phishstats.py
Determine whether an IP Address is malicious or not from PhishStats API
> Implement sfp_phishstats.py

- modules/sfp_maltiverse.py
Check if an IP Address is malicious, and gather data from Maltiverse API
> Implement sfp_maltiverse

- THANKYOU
- modules/sfp_badpackets.py
> Correct typos and clean up style in Bad Packets module

- modules/sfp_keybase.py
Replace literal \n to linebreak
> Bugfix to sfp_keybase

- sfdb.py
I hadn't noticed that one of the protected database code blocks was calling another protected function in an exception handler. I changed the threading.Lock to threading.RLock to allow reentrant locking by the same thread. 
I was also seeing some degraded performance during startup and when saving spiderfoot configs. It seems that moving the commit inside the config update loop had a significant impact. I moved the commit out of the loop and expanded the scope of the lock for the entire loop.
> Pull db commits out of config set/update loops. Use RLock.

- modules/sfp_accounts.py
Some of the sites in the WebBreacher site list return a 200 status code for both a found account and a missing account. The previous code was considering the account to be found if the status code matched without further testing the account_existence_string. This was resulting in false positives. I simplified the check so that if the status code and the account_existence_string match, then the account is considered found. Otherwise, the account wasn't found. It is possible that neither the account found and account missing conditions are satisfied, but since the check is not using 3-state logic, I defaulted to either found or not found.
For the site scanning, the previous code was batching groups of sites and running the batches sequentially. This meant that a slow site would hold up the …
> Changed account existence checks. Site check performance improvements.

- modules/sfp_accounts.py
Used the 'valid' field in the web site JSON file.
Fixed caching with no distrusted sites. After eliminating the invalid accounts checks, there are no distrusted sites. Trying to save an empty list to the cache is a no-op. The next time the cache was checked, there was no entry so all the sites were checked again. I added a sentinel string ("None") to indicate there are no distrusted sites.
> Ignore invalid accounts based on JSON.

- sflib.py
> Modified the cache write to use UTF8 file encoding.

- sflib.py
This adds documentation for the majority of sflib. Some items are marked `TBD` for now.
Also ninja adds a couple of guard clauses.
> Document sflib functions

- test/unit/test_spiderfootscanstatus.py
Re-add tests deleted in #528.
Not a particularly useful test suite, but at least it touches the code.
> tests: re-add test/unit/test_spiderfootscanstatus.py

- Dockerfile
Update based on suggestion from @sucramx in #541. I've verified that I was able to create and run a container with the modification.
> Specify alpine base image version in Dockerfile

- sfdb.py
Add a data type for recording affiliate domains which are not registered
(or have expired).
> sfdb: Add AFFILIATE_DOMAIN_UNREGISTERED data type

- .travis.yml
If you enable GitHub's Travis CI integration, this configuration will run the SpiderFoot unit tests on each commit. https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github
> Adding Travis CI config

- modules/sfp_dnsraw.py
Also adds support for Sender ID `spf2.0` SPF records and cleans up the code a lot.
> sfp_dnsraw: add support for CNAME records

- sfdb.py
> Return empty list for failed search

- sfdb.py
> sfdb: Ensure search function returns a list

- test/unit/test_spiderfootcli.py
Updates CLI unit tests and resolves comments:
* https://github.com/smicallef/spiderfoot/commit/0fc8f898f48f12658b77d4a2fc83b31f1ea72ae5#r40280031
* https://github.com/smicallef/spiderfoot/commit/0fc8f898f48f12658b77d4a2fc83b31f1ea72ae5#r40280057
> test_spiderfootcli: Update sfcli unit tests

- sfwebui.py
This is required for the `Force Layout` button on the scan Graph view.
> sfwebui: Add blob: to CSP script-src

- modules/sfp_badipscom.py
> sfp_badipscom: rewrite and remove unused code

- dyn/scaninfo.tmpl
> sfwebui: use placeholder for empty chart on scaninfo page

- dyn/scaninfo.tmpl
https://github.com/smicallef/spiderfoot/issues/700#issuecomment-673971322
> sfwebui: Check if status is ERROR-FAILED rather than FAILED

- sfdb.py
- sflib.py
- test/unit/test_spiderfootevent.py
> sfdb: Add event attribute validation and error handling

- sfdb.py
- test/unit/test_spiderfootdb.py
> sfdb: validate search() search criteria

- modules/sfp_emailrep.py
I have no idea if this works. I haven't tested with a key.
Fixes #688
> sfp_emailrep: Add support for API key

- README.md
Leaving this here until you decide the test coverage is high enough that you want to show it off. Currently 48%.
> README: Add Codecov badge

- modules/sfp_digitaloceanspace.py
- modules/sfp_googleobjectstorage.py
- modules/sfp_s3bucket.py
Make the logic for testing the existence of buckets more legible.
> Clean up bucket querying logic.

- modules/sfp_dnsresolve.py
- setup.cfg
> flake8-bugbear: resolve B007 violation

- modules/sfp_dronebl.py
- modules/sfp_recondev.py
- test/unit/modules/test_sfp_dnsraw.py
- test/unit/modules/test_sfp_dronebl.py
- test/unit/modules/test_sfp_recondev.py
- test/unit/modules/test_sfp_sorbs.py
- test/unit/modules/test_sfp_spamcop.py
- test/unit/modules/test_sfp_spamhaus.py
- test/unit/modules/test_sfp_uceprotect.py
Some minor updates now that api.recon.dev appears to be legacy.
> Naming and API updates for recon.dev

- modules/sfp_pastebin.py
- modules/sfp_psbdmp.py
> sfp_pastebin / sfp_psbdmp : check for false positives

- .github/ISSUE_TEMPLATE.md
This is a very simplistic issue template. Users will see this text when creating a new issue via the Issues page on the Git repository.
> Add .github/ISSUE_TEMPLATE.md

- modules/sfp_template.py
Let's reduce some boilerplate code
> Propose shortcut function for sfp_template

- dyn/scaninfo.tmpl
- static/js/spiderfoot.scanlist.js
> sfwebui: fix scan status badge

- sflib.py
> sflib: log and raise exception in sf._dblog

- modules/sfp_fullcontact.py
> sfp_fullcontact: code cleanup

- setup.cfg
- sfcli.py
- sflib.py
- test/unit/test_spiderfoot.py
Ninja edit: removes `fatal=True, splitLines=True` arguments from `SpiderFoot.optValueToData()` function.
> tests: resolve flake8-return violations

- sflib.py
- test/unit/test_spiderfoot.py
> SpiderFoot: validate fetchUrl() URL scheme

- modules/sfp_hackertarget.py
Also removes this module from the `Passive` use case.
> sfp_hackertarget: code cleanup

- sfwebui.py
> sfwebui: Add error_page_401 handler

- modules/sfp_cleanbrowsing.py
- modules/sfp_cloudflaredns.py
- modules/sfp_comodo.py
- modules/sfp_norton.py
- modules/sfp_opendns.py
- modules/sfp_quad9.py
- modules/sfp_yandexdns.py
> modules: Use dns.resolver.Resolver.resolve()

- README.md
> README: Update SpiderFoot module count to 200

- modules/sfp_accounts.py
- modules/sfp_archiveorg.py
- modules/sfp_azureblobstorage.py
- modules/sfp_base64.py
- modules/sfp_creditcard.py
- modules/sfp_crxcavator.py
- modules/sfp_digitaloceanspace.py
- modules/sfp_dnsdb.py
- modules/sfp_emailcrawlr.py
- modules/sfp_fringeproject.py
- modules/sfp_googleobjectstorage.py
- modules/sfp_gravatar.py
- modules/sfp_iban.py
- modules/sfp_intelx.py
- modules/sfp_jsonwhoiscom.py
- modules/sfp_keybase.py
- modules/sfp_onyphe.py
- modules/sfp_riskiq.py
- modules/sfp_s3bucket.py
- modules/sfp_scylla.py
- modules/sfp_tool_whatweb.py
- modules/sfp_xforce.py
- test/unit/modules/test_sfp_base64.py
Bunch of module bug fixes. Currently a work-in-progress.
> Various module bug fixes.

- sf.py
Group functionality and decrease complexity, indentation, branches and lines of code.
> sf: code cleanup

- sf.py
- test/unit/test_spiderfoot_module_loading.py
> sf: allow modules to have more than one category

- Dockerfile
Fixes #1074.  Tested and working.
> Fixed permission error with logs directory when running in Docker

- requirements.txt
> requirements: Bump networkx==2.3 to networkx>=2.5

- modules/sfp_leakix.py
Hi, this should increase the number of results and matches when querying/finding domains on LeakIX
> sfp_leakix: domain support, listen and notify

- sf.py
- sfcli.py
- sfwebui.py
- spiderfoot/__init__.py
- test/conftest.py
- test/integration/test_sfwebui.py
This should decrease mistakes and make release updates easier.
> spiderfoot: Use spiderfoot.__version__ for version instead of config dict

- modules/sfp_reversewhois.py
- test/unit/modules/test_sfp_reversewhois.py
https://www.reversewhois.io/ is a free search engine which finds whois records by email address or email domain. This module makes a single domain query which returns all domains containing matching email addresses in their whois records.
> Added reversewhois.io module

- dyn/scandelete.tmpl
- sfwebui.py
- static/js/spiderfoot.scanlist.js
- test/unit/test_spiderfootwebui.py
less functions, less URL routes, less code, less complexity
> sfwebui: Merge scandelete and scandeletemulti URL routes into scandelete

- .pylintrc
https://google.github.io/styleguide/pyguide.html
> pylint: Use Google Python style

- dyn/opts.tmpl
> sfwebui: Show module descriptions and meta info on module settings page

- modules/sfp_dronebl.py
> sfp_dronebl: Update DNS response blacklist

- README.md
- modules/sfp_spyse.py
Spyse v3 API has been deprecated.
See API references: https://spyse-dev.readme.io/reference/quick-start
This pull request will update the module for Spyse API v4 and add more events to the module.
New events that Spyse module will emit:
OPERATING_SYSTEM
COUNTRY_NAME
VULNERABILITY
COMPANY_NAME
WEBSERVER_TECHNOLOGY
IP_ADDRESS
IPV6_ADDRESS
DNS_SPF
DNS_TEXT
PROVIDER_DNS
DOMAIN_REGISTRAR
HTTP_CODE
EMAILADDR
SSL_CERTIFICATE_ISSUED
SSL_CERTIFICATE_ISSUER
WEB_ANALYTICS_ID
> Update Spyse module

- modules/sfp_sublist3r.py
- test/unit/modules/test_sfp_sublist3r.py
The [Sublist3r tool](https://github.com/aboul3la/Sublist3r) hosts its own passive DNS API at https://api.sublist3r.com. This is one of the primary data sources for the tool, which is actively maintained and has over 6,000 stars on GitHub. Since it is technically an undocumented API, this module is careful to clean, deduplicate, and validate the data before raising events.
> Added Sublist3r PassiveDNS module

- modules/sfp_dnsdumpster.py
- test/unit/modules/test_sfp_dnsdumpster.py
Scrapes subdomains (in a safe and responsible manner ;) from https://dnsdumpster.com/.
> Added DNSDumpster module

- test/unit/modules/test_sfp_dnsdumpster.py
- test/unit/modules/test_sfp_sublist3r.py
These tests do not make sense and should be skipped.
> Tests: modules: skip invalid tests

- spiderfoot/static/css/dark.css
> Fixed visual bug in dark theme modals

- modules/sfp_dnsneighbor.py
This modifies `sfp_dnsneighbor`  to search the IP's subnet instead of a hardcoded distance in either direction. E.g. with the default netmask of `/28`, the IP of `1.2.3.4` would generate DNS neighbors beginning with `1.2.3.0` and ending with `1.2.3.15`. Before, it would dip down past the subnet boundary into `1.2.2.250`.
> In sfp_dnsneighbor, use netmask to respect subnet boundaries

- modules/sfp_emailformat.py
This eliminates the "John Smith" related false positives.
> sfp_emailformat: Extract email addresses from tbody

- modules/sfp_tool_cmseek.py
Also fixes UTF-8 parsing bug when checking `stdout`.
> sfp_tool_cmseek: Cleanup error handling; report CMS version

- modules/sfp_dehashed.py
- modules/sfp_grayhatwarfare.py
- modules/sfp_haveibeenpwned.py
- modules/sfp_onioncity.py
- modules/sfp_seon.py
- modules/sfp_sociallinks.py
> Modules: Add missing apiKeyInstructions

- modules/sfp_blocklistde.py
> sfp_blocklistde: Cleanup

- modules/sfp_talosintel.py
> sfp_talosintel: Cleanup and update blacklist url

- modules/sfp_isc.py
> sfp_isc: Cleanup

- modules/sfp_vxvault.py
> sfp_vxvault: Cleanup

- modules/sfp_phishtank.py
> sfp_phishtank: Cleanup

- modules/sfp_botvrij.py
> sfp_botvrij: Cleanup

- modules/sfp_voipbl.py
This PR also updates the URL to use HTTPS and updates the module description which was incorrect.
> sfp_voipbl: Cleanup

- modules/sfp_alienvaultiprep.py
> sfp_alienvaultiprep: Cleanup

- modules/sfp_multiproxy.py
> sfp_multiproxy: Cleanup

- modules/sfp_torexits.py
> sfp_torexits: Cleanup

- modules/sfp_fortinet.py
> sfp_fortinet: Cleanup and fix matching

- modules/sfp_cybercrimetracker.py
> sfp_cybercrimetracker: Cleanup

- modules/sfp_openphish.py
> sfp_openphish: Cleanup

- sfcli.py
* Minor style cleanup (mostly format string)
* Minor reduction in cyclomatic complexity
* Fix error handling for command line arguments of `int` type (instead of crashing)
* Fix error handling for `shlex` invalid commands (instead of crashing)
* Adds support for `gexf` to `export` command.
> sfcli: Cleanup

- modules/sfp_spider.py
Fixes #1312
`TARGET_WEB_CONTENT` for binary data is now stored as a byte string (instead of crashing the module):
> sfp_spider: Store TARGET_WEB_CONTENT web content event as string

- requirements.txt
- sfwebui.py
- spiderfoot/static/css/dark.css
- spiderfoot/static/css/spiderfoot.css
- spiderfoot/static/js/spiderfoot.scanlist.js
- spiderfoot/templates/scaninfo.tmpl
- test/integration/test_sfwebui.py
- test/unit/spiderfoot/test_spiderfootplugin.py
- test/unit/test_spiderfootwebui.py
This PR adds an "Excel" export format in the web UI.
Each event type gets its own sheet:
> Excel Export Functionality

- .gitignore
> gitignore: Ignore reports, IDE, documentation

- sflib.py
> sflib: Add annotations and docstrings

- modules/sfp_callername.py
- modules/sfp_commoncrawl.py
- modules/sfp_crossref.py
- modules/sfp_flickr.py
- modules/sfp_h1nobbdde.py
- modules/sfp_hackertarget.py
- modules/sfp_myspace.py
- modules/sfp_open_passive_dns_database.py
- modules/sfp_openbugbounty.py
- modules/sfp_pgp.py
- modules/sfp_skymem.py
- modules/sfp_twitter.py
> modules: cast fetchUrl content as string in calls to findall()

- spiderfoot/templates/scaninfo.tmpl
Fix HTML rendering issue introduced in #1336.
> sfwebui: Fix scan info download logs HTML closing tag

- test/acceptance/scan.robot
These tests would have caught the HTML rendering issue introduced in #1336 and fixed in #1340.
> Tests: Update acceptance tests

- .github/workflows/codeql-analysis.yml
The CodeQL workflow takes 10+ minutes to complete. Where as the entire test suite completes in ~5 minutes.
> Actions: CodeQL: Run on push to master not PRs

- sfwebui.py
- test/unit/test_spiderfootwebui.py
> sfwebui: Use scan name for CSV/Excel/GEXF export filename

- modules/sfp_email.py
Also fixes a bug introduced in 604097d8e92424c54b275d844ad7f464808af894 where the module would stop iterating through potential email addresses once an invalid email was identified.
> sfp_email: Cleanup

- spiderfoot/static/js/spiderfoot.js
> sfwebui: Add formatting and icon to alertify notifications

- README.md
> README: Update directory in install instructions

- modules/sfp_keybase.py
* Allow searching for usernames by `DOMAIN_NAME`.
* Prevent returning empty `RAW_RIR_DATA` when no results are returned: `{'status': {'code': 0, 'name': 'OK'}, 'them': [None]}`
* Fix failsafe username case sensitive match. Now ignores case.
> sfp_keybase: Cleanup and add support for DOMAIN_NAME events

- modules/sfp_ripe.py
Adds support for:
* NETBLOCKV6_OWNER
* NETBLOCKV6_MEMBER
* IPV6_ADDRESS
> sfp_ripe: Add support for IPv6

- modules/sfp_dnsresolve.py
> sfp_dnsresolve: Add support for NETBLOCKV6_OWNER

- modules/sfp_hackertarget.py
These functions require completing a CAPTCHA.
> sfp_hackertarget: Remove IPv4 TCP/UDP port scanning

- modules/sfp_robtex.py
> sfp_robtex: Add support for IPv6

- modules/sfp_censys.py
Also fixes:
* Error where `rec` was undefined
* API response parsing
* Open port detection
* Operating system detection
> sfp_censys: Cleanup

- modules/sfp_alienvault.py
- setup.cfg
> sfp_alienvault: Add support for IPv6; and search URLs for domains

- modules/sfp_fraudguard.py
> sfp_fraudguard: Add support for IPv6

- modules/sfp_viewdns.py
I have *not* tested these changes.
> sfp_viewdns: Cleanup; Add verbose debug output; Add to Footprint category

- modules/sfp_greynoise.py
- requirements.txt
The following includes some recommended updates to the GreyNoise lookup.  Please feel free to accept or reject as makes sense:
List of changes:
- Migrates individual IP lookups to use IP Lookup endpoints
- Adds support for RIOT dataset - IP lookups check both now
- Updated broken Logo Links
- Update GreyNoise Visualizer URLs
- Corrected display for "GreyNoise" from "Greynoise"
> [sfp_greynoise] Suggested Update for GreyNoise Lookup

- spiderfoot/static/js/spiderfoot.js
Fixed problems mentioned in Issue #1612. I fixed the dark mode toggle on chromium-based browsers and ensuring that the toggle responds as expected. I also corrected the Label next to the toggle so that it displays "Dark Mode" when the theme is in Dark Mode and "Light Mode" otherwise.
> Darkmodefix Issue #1612

- .vscode/settings.json
- modules/sfp_names.py
- modules/sfp_stackoverflow.py
Hi! 
I've made a simple StackOverflow module. You can search by domain, and a RAW_RIR_DATA will return for any questions where the domain was seen, with the URL to the question prepended.  Additionally, email and IP addresses are extracted, and the username seen posting the question.
I haven't written python in a long time, but I tried to follow best practices - let me know if I can improve!
> StackOverflow module

- modules/sfp_hackertarget.py
> sfp_hackertarget: set errorState when rate limit is exceeded

- modules/sfp_company.py
Fixes https://github.com/smicallef/spiderfoot/issues/1630
> Added missing commas

- spiderfoot/db.py
> Fix implicit string concatenation

- sfscan.py
This resolves the issue for which there was an attempted patch in #1127.
To reproduce this issue, run SpiderFoot without a cached TLD list from a host which cannot retrieve the TLD list from `publicsuffix.org`. The easiest way to achieve this is to set an invalid DNS server in Settings. Alternatively, you could disconnect the host from the Internet.
Note to self: we should probably also verify that the configured DNS server works during scan init.
Output:
```
2022-04-17 17:15:24,702 [INFO] sfwebui : Waiting for the scan to initialize...
2022-04-17 17:15:24,774 [INFO] sflib : Downloading configuration data from: https://publicsuffix.org/list/effective_tld_names.dat
2022-04-17 17:15:30,181 [ERROR] sflib : Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: …
```
> sfscan: Abort scan with ERROR-FAILED status if TLD list is empty

- sfcli.py
- spiderfoot/correlation.py
> Fix missing `f` prefix on f-strings

- README.md
- modules/sfp_stackoverflow.py
I was tinkering with spiderfoot and ran across this typo which was the smallest of all annoyances anyone could ever experience. However, I figured it should be fixed.
> Fixed smallest typo for stackecxchange

- sflib.py
resolved bug reported by Alek#8500 on the discord server
> issue from discord resolved

- modules/sfp_censys.py
> sfp_censys: Add support for IPv6; report software and operating system

- spiderfoot/helpers.py
- test/unit/spiderfoot/test_spiderfoothelpers.py
> SpiderFootHelpers: extractLinksFromHtml: Use BeautifulSoup lxml parser

- modules/sfp_greynoise.py
- modules/sfp_greynoise_community.py
- Adds new sfp_greynoise_community that is based on sfp_greynoise but uses the GreyNoise Community API
- Minor updates to sfp_greynoise for some URLs
> Add GreyNoise Community Module

- sflib.py
Created a pull request with the aforementioned issue.
> Fixed UnicodeDecodeError

- spiderfoot/templates/error.tmpl
> Templates: error: Use correct support email address

- test/unit/test_modules.py
This test now passes and can be uncommented.
> test: unit: modules: Ensure each module dataSource has a description

- spiderfoot/helpers.py
This PR adds additional type annotations to a handful of functions in helpers.py in order to their improve clarity.
> Add type annotations to functions in spiderfoot/helpers.py

- sfcli.py
> sfcli: Add help for 'export' command

- spiderfoot/helpers.py
> SpiderFootHelpers: buildGraphGexf: set color alpha channel to 1

- spiderfoot/static/js/spiderfoot.js
> sfwebui: Use user-defined doc root path for static JS
