- modules/sfp_accounts.py
- modules/sfp_adblock.py
- modules/sfp_blacklist.py
- modules/sfp_cookie.py
- modules/sfp_dns.py
- modules/sfp_filemeta.py
- modules/sfp_geoip.py
- modules/sfp_honeypot.py
- modules/sfp_intfiles.py
- modules/sfp_ir.py
- modules/sfp_malcheck.py
- modules/sfp_pastebin.py
- modules/sfp_portscan_tcp.py
- modules/sfp_shodan.py
- modules/sfp_similar.py
- modules/sfp_social.py
- modules/sfp_socialprofiles.py
- modules/sfp_spider.py
- modules/sfp_sslcert.py
- modules/sfp_strangeheaders.py
- modules/sfp_virustotal.py
- modules/sfp_websvr.py
- sflib.py
- sfwebui.py
This accomplishes three things:
* More PEP 8 Compliant.
* Removed redundant backslashes within brackets.
* Replaced all depreciated 'has_key()' instances with 'in'.
--------
'has_key()' has been depreciated in Python 2 and removed in Python 3. Additionally there is a performance gain by using 'in'.
To put this in perspective:
```
$ python2 -mtimeit -s'd=dict.fromkeys(range(99))' '12 in d'
10000000 loops, best of 3: 0.0339 usec per loop
$ python2 -mtimeit -s'd=dict.fromkeys(range(99))' 'd.has_key(12)'
10000000 loops, best of 3: 0.116 usec per loop
```
Due to the quantity of 'has_key()' instances that were replaced, this may provide a serious performance increase, or at least some sort of performance increase.
--------
References:
https://docs.python.org/2/library/stdtypes.html#dict.has_key
> Depreciation Resolution and More PEP 8

- modules/sfp_dnscommonsrv.py
- sfdb.py
This PR add a module that will try to find servers using SRV records. This can be used to find AD servers or similar interesting system for internal pentesting, or external target (such as SIP, XMPP, etc) for exteranl intelligence gathering.
It also add a new record, both for UX and to potentially later be consumed by others modules.
> Add a module to detect SRV records

- Dockerfile
I have 2 changes:
1. The version of Spiderfoot has been updated to the latest version (2.11.0 as of now)
2. Added `pip install wheel` as I had the following error:
```
Running setup.py bdist_wheel for mako ... error
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Gx291P/mako/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2dyHevpip-wheel- --python-tag cp27:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel'
```
Now the build works fine.
> Updated version and added wheel

- modules/sfp_mnemonic.py
Move `sfp_mnemonics` from `Search Engines` to `Passive DNS` category, in line with `sfp_hackertarget` and `sfp_robtex`.
I didn't realize `Passive DNS` was a valid category at the time.
> Move sfp_mnemonics to Passive DNS category

- modules/sfp_viewdns.py
Not sure how this happened.
Looks like a find/replace for `.info` with `.com` may have gone wrong. There are no other instances of `"to.infopletely"` in the modules directory.
It appears this typo has always existed in the `sfp_viewdns` module:
* https://github.com/smicallef/spiderfoot/blob/ed9b7fd5a9e972832d1d347235b915eeded4fb13/modules/sfp_viewdns.py
> Fix comment

- sfscan.py
Gracefully rescue `ImportError` if module no longer exists - Fix #188
I chose to call `self.ts.sf.error` with `False`, so as to allow the scan to continue executing despite the import error.
This seemed like the most reasonable approach, as an import error is most likely to occur either when re-running a scan after a deprecated module has been deleted from the repository, or due to a syntax error while actively developing a module, in which case it's your own fault.
On the other hand, allowing the scan to continue causes the scan to show up as `FINISHED` state, rather than `ERROR`, which may be confusing to users. Also, rescuing from `ImportError` could potentially (?) hide bugs lurking in the module code which caused the module to fail.
Ideally, the `ImportError` subclass …
> Gracefully rescue ImportError if module no longer exists - Fix #188

- .pylintrc
Add a `.pylintrc` file, to make pylint less useless, as a step towards PEP8 compliance.
Generated with `pylint --generate-rcfile`
Added `e` and `sf` as "good" variable names.
Added `output-format=parseable`
```
Using config file /root/Desktop/spiderfoot/.pylintrc
************* Module modules.sfp_phone
modules/sfp_phone.py:18: [E0401(import-error), ] Unable to import 'phonenumbers'
************* Module modules.sfp_filemeta
modules/sfp_filemeta.py:16: [E0401(import-error), ] Unable to import 'openxmllib'
modules/sfp_filemeta.py:17: [E0401(import-error), ] Unable to import 'exifread'
************* Module modules.sfp_whois
modules/sfp_whois.py:14: [E0401(import-error), ] Unable to import 'whois'
************* Module modules.sfp_portscan_tcp
modules/sfp_portscan_tcp.py:90: [E1101(no-member), …
```
> Make pylint less useless

- modules/sfp_shodan.py
Add `WEB_ANALYTICS_ID` to `sfp_shodan` watched events.
Allows searching for similar sites using the same analytics IDs, such as Google analytics, by using the `http.html:` filter. Saves results as `SEARCH_ENGINE_WEB_CONTENT`.
Saving as `SEARCH_ENGINE_WEB_CONTENT` is not ideal, but this is currently what the module also does for `DOMAIN_NAME` events. Ideally, in the future, the response should be parsed and the appropriate events returned. I consider this outside the scope of this PR.
The results from this test are usually not as good as SpyOnWeb, however, it's nice to have options.
Also, **this PR ninja patches a bug** where the URL should use `&` instead of `?` which was causing the API to return `401`.
> Add WEB_ANALYTICS_ID to sfp_shodan watched events

- sfwebui.py
Set `application/json` content-type header for `/query` route.
```
http://127.0.0.1:5001/query?query=select+"<body+onload=alert(window.location)>"+from+sqlite_master
```
```
http://127.0.0.1:5001/query?query=select+"
<script>
var xhttp = new XMLHttpRequest()%3b
xhttp.onreadystatechange = function() {
if(this.readyState==4 %26%26 this.status==200) alert(this.responseText)
}%3b
xhttp.open('GET', '/query?query=select+*+from+tbl_config%253b--', true)%3b
xhttp.send()%3b
<%2fscript>"
```
> Set application/json content-type header

- modules/sfp_github.py
- modules/sfp_myspace.py
- modules/sfp_slideshare.py
- modules/sfp_spyonweb.py
- modules/sfp_twitter.py
Add error handling to gracefully catch potential errors when splitting `eventData` strings which (somehow) are not in the expected format.
Untested. Copy pasta.
As per https://github.com/smicallef/spiderfoot/pull/261#discussion_r281919872
> Catch string split errors

- modules/sfp_numinfo.py
Add sfp_numinfo.
Retrieves only email addresses as `EMAILADDR`. Stores the raw JSON data as `RAW_RIR_DATA`.
It's possible to retrieve other data, such as name and location, but the accuracy is questionable, and sometimes complete garbage. Without validation, it's best to simply store the response as `RAW_RIR_DATA` for now.
Here's some sample data for reference.
```
<script type="application/ld+json">
{
"@context": "http://schema.org",
"@type": "Person",
"address": {
"@type": "PostalAddress",
"addressLocality": "LIMA",
"addressRegion": "LIMA",
"postalCode": "",
"streetAddress": "123 fake st"
},
"email": "mailto:someone@example.com",
"jobTitle": "Phone Owner",
"name": "John Smith",
"telephone": "5111111123",
"url": "5111111123.numinfo.net/"
}
</script>
```
> Add sfp_numinfo

- dyn/newscan.tmpl
- sflib.py
Permit `PHONE_NUMBER` as scan target.
Using a phone number as a scan target is now viable with the modifications to `sfp_phone` (#276) and `sfp_neutrinoapi` (#280) modules, and addition of `sfp_numverify` (#275) and `sfp_numinfo` (#283) modules.
It's also an easy regex which shouldn't result in false positive matches. It could be improved by using the `python-phonenumbers` library to validate the user input.
> Permit PHONE_NUMBER as scan target

- dyn/scaninfo.tmpl
- static/css/spiderfoot.css
In installations with docroot defined, the graph view did not show up
due to missing definitions.
Fixes also CSS issue where the table sort icon was missing on docroot
enabled installations.
> Fix docroot related errors on graph view and css

- sf.py
Check `passwd` file is readable, and prevent the follow stacktrace caused by malformed passwd entries:
```
$ ./sf.py 
Attempting to verify database and update if necessary...
Starting web server at http://127.0.0.1:5001 ...
Traceback (most recent call last):
File "./sf.py", line 381, in <module>
u, p = line.strip().split(":")
ValueError: need more than 1 value to unpack
```
> Fix passwd and cert file checks

- sfcli.py
```
https://github.com/PyCQA/pylint/issues/1411
```
**Before**
```
Using config file /root/Desktop/spiderfoot/.pylintrc
************* Module sfcli
sfcli.py:355: [E1101(no-member), SpiderFootCli.request] Instance of 'LookupDict' has no 'ok' member
```
**After**
```
Using config file /root/Desktop/spiderfoot/.pylintrc
```
> pylint: disable=no-member

- sfwebui.py
http://python-future.org/compatible_idioms.html#stringio
Libraries and `ext` dependencies also need to be reviewed:
```
modules/sfp_filemeta.py:19:from StringIO import StringIO
sfwebui.py:26:from StringIO import StringIO
ext/stem/control.py:253:  from StringIO import StringIO
ext/stem/response/__init__.py:50:  from StringIO import StringIO
```
> from io import StringIO

- modules/sfp_sslcert.py
This PR fixes a bug in the `sfp_sslcert` module handling of `IP_ADDRESS` events.
The module prepended a URL scheme to the FQDN:
```python
if eventName == "IP_ADDRESS":
fqdn = "https://" + eventData
```
And then attempts to use this string in a TCP socket `connect` call, which will obviously fail, resulting in the following error:
```
Unable to SSL-connect to https://xx.xx.xx.xx
```
Fixing this required moving the `self.opts['tryhttp']` check to the `if eventName == "LINKED_URL_INTERNAL":` conditional, which is where it belonged anyway, as this option is irrelevant for the other events this module watches (`INTERNET_NAME`, `IP_ADDRESS`).
> Fix sfp_sslcert handling of IP_ADDRESS events

- modules/sfp_hackertarget.py
Add `httpHeaders` function to `sfp_hackertarget` module to retrieve the HTTP headers for each `IP_ADDRESS`.
> Add httpHeaders to sfp_hackertarget

- sflib.py
Exposes urllib `verify` in the `sflib.fetchUrl` function (default: `False`)
This allows modules to override SSL validation. Which should eventually be useful, when SF eventually moves to opt-out rather than opt-in for SSL validation.
> Add verify option to sflib.fetchUrl

- modules/sfp_sslcert.py
Add `getSubjectAltNames` function to `sfp_sslcert`.
This will be useful when SAN parsing is eventually added.
This PR also cleans up some of the module code.
* `getIssued` and `getIssuer` now return a `String`, permitting code reuse
* `checkHostMatch` now uses `getIssued`, rather than using duplicated code and error handling
* `checkHostMatch` now uses the newly added `getSubjectAltNames` function
* `checkHostMatch` now uses a pretty `list()` of hosts, rather than an ugly loop and concatenated string
* `checkHostMatch` now returns a `Boolean` (`True` if the host matches), permitting code reuse
> Add getSubjectAltNames to sfp_sslcert

- sfwebui.py
After scan deletions, redirect the user to docroot instead of "/".
> Redirect to docroot instead of "/"

- modules/sfp_accounts.py
- modules/sfp_bingsharedip.py
- modules/sfp_circllu.py
- modules/sfp_dnscommonsrv.py
- modules/sfp_dnszonexfer.py
- modules/sfp_hackertarget.py
- modules/sfp_peegeepee.py
- modules/sfp_riskiq.py
- modules/sfp_robtex.py
- modules/sfp_spider.py
Print debug message when event is ignored.
Also, ensure `"Received event, " + eventName + ", from " + srcModuleName` is printed, regardless of whether the event is ignored.
Untested.
> Print debug message when event is ignored

- sfcli.py
Alternatively, rather than exiting, you may want to silently catch `KeyboardInterrupt`, and print a nice `yo, type exit to exit` message.
> Catch KeyboardInterrupt for prettier exiting

- modules/sfp_shodan.py
Small bug fix.
`http.html` filter worked fine for simple strings such as Google Analytics IDs, but fails on more complex strings which contain characters such as '+', likely due to URL encoding.
Using quotes around the query, in combination with `urllib.encode` resolves this.
> Quote http.html filter query

- modules/sfp_shodan.py
Whitelist useful analytics networks for Shodan.
The majority of the analytics IDs currently supported are based on DNS `TXT` records, which won't appear in Shodan using `http.html` filter.
> Whitelist useful analytics networks

- sfwebui.py
Prior to this PR, the following request would cause a HTTP 500 Internal Server Error.
```
curl -isk -X POST http://127.0.0.1:5001/scanexportjsonmulti -d "ids=anything"
```
This PR ensures empty JSON is returned instead:
```
HTTP/1.1 200 OK
Content-Length: 2
Content-Disposition: attachment; filename=SpiderFoot.json
Server: CherryPy/17.4.1
Pragma: no-cache
Date: Sun, 14 Jul 2019 15:56:02 GMT
Content-Type: application/json; charset=utf-8
{}
```
> Validate ids POST param for scanexportjsonmulti

- modules/sfp_accounts.py
- modules/sfp_dnsbrute.py
- modules/sfp_junkfiles.py
- modules/sfp_portscan_tcp.py
- modules/sfp_tldsearch.py
- sf.py
- sflib.py
- sfscan.py
- sfwebui.py
Use `random.SystemRandom()` rather than `random`.
Keeps `dlint` happy. Most of these changes don't require system randomness, but shouldn't hurt.
```
$ python2 -m flake8 --select=DUO *.py 
```
> Use random.SystemRandom()

- modules/sfp_bgpview.py
Add BGPView `sfp_bgpview` module for review / testing.
Approximately 1,000 times faster than `sfp_ripe` (+/- 1,000), as all ASN peers are retrieved in a single API query.
Supports IPv4 and IPv6.
Does not retrieve `BGP_AS_OWNER`.
> Add sfp_bgpview

- modules/sfp_tool_whatweb.py
Add `sfp_tool_whatweb` module to wrap [whatweb](https://github.com/urbanadventurer/whatweb).
Ideally this module would instead run WhatWeb over the stored HTTP headers and HTTP response body. However, Spiderfoot stores these as separate events, and WhatWeb works best when both are present.
```python
def producedEvents(self):
return ['RAW_RIR_DATA', 'WEBSERVER_BANNER', 'WEBSERVER_TECHNOLOGY']
```
The `WEBSERVER_BANNER` and `WEBSERVER_TECHNOLOGY` returned events are effectively a duplicate of whatever the `sfp_webserver` module would return. However, this module won't run unless the path to WhatWeb is configured, so I see no harm in adding it to the repository. Also, the output is stored as `RAW_RIR_DATA`, which is arguably more valuable, despite not producing any events.
Further efforts …
> Add sfp_tool_whatweb

- sfwebui.py
Hide stack traces unless debugging is enabled. Returns a minimalist error page which should, in theory, not raise any additional errors unless something has gone horribly wrong.
Uses the default CherryPy `_cperror.get_error_page()` page template to format the stack trace nicely if `debug` is enabled. This is the same behaviour as prior to this PR.
> Hide stack traces unless debugging is enabled

- modules/sfp_email.py
- modules/sfp_emailformat.py
- modules/sfp_pgp.py
- modules/sfp_skymem.py
- sflib.py
This PR abstracts email regex parsing into a separate `sf.parseEmails()` function in `sflib`, which operates in a similar fashion to `sf.parseLinks()`.
This decreases repetition, decreases lines of code, and consolidates functionality such that future parsing enhancements are easier. For example, in the future we may want to add functionality for fuzzy matching, which matches strings such as `recipient<at>domain<dot>tld`, `recipient(at)domain.tld`, etc.
This also has the added advantage that, in the future, modules can simple shove data into this function and see what falls out.
I've done some light testing to ensure the modules don't throw an error, but I haven't tested this PR thoroughly.
> Add sf.parseEmails function to extract emails from strings

- modules/sfp_email.py
- modules/sfp_emailformat.py
- modules/sfp_flickr.py
- modules/sfp_pgp.py
- modules/sfp_skymem.py
Make use of `getTarget()` `includeChildren=True`, `includeParents=True` for emails
Also updates the `fp_flickr` module to make use of the new `parseEmails()` function.
Also updates the email modules to accept both `INTERNET_NAME` and `DOMAIN_NAME` as `watchedEvents`, instead of only `DOMAIN_NAME`.
> Use getTarget() includeChildren=True, includeParents=True for emails

- modules/sfp_fsecure_riddler.py
Add `sfp_fsecure_riddler` module.
F-Secure Riddler is apparently approaching end of life. The website has said that for a while, and doesn't appear to offer an EOL date.
The module won't run unless you specify login credentials. Registration is currently disabled. But if you have an account, this might be useful.
There's more info that could be grabbed (response data is saved as `RAW_RIR_DATA`), but I didn't put much effort into this module, due to alleged approaching EOL.
```¯\_(ツ)_/¯```
> Add sfp_fsecure_riddler module

- modules/sfp_fsecure_riddler.py
- modules/sfp_mnemonic.py
- modules/sfp_ssltools.py
Validate `IP_ADDRESS` and `IPV6_ADDRESS` events.
Requires #399 for `validIP6()` function.
> Validate IP_ADDRESS and IPV6_ADDRESS events

- modules/sfp_dnsraw.py
Skip SPF domains containing underscore. It is common for SPF records to contain a `_spf.domain.tld` record.
Also adds `includeParents=True` for `getTarget()`.
> Skip SPF domains containing underscore

- Dockerfile
Building the docker image results in an error (see below). I've added a dependency for `libffi-dev` to make sure building the `cffi` Python package succeeds.
```
[...]
Failed to build cffi
Installing collected packages: setuptools, wheel, pycparser, cffi
Running setup.py install for cffi: started
Running setup.py install for cffi: finished with status 'error'
Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-QI6b9d/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Rn5Dfb/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-94Dj3e --compile:
Package libffi was not found in the …
```
> Add missing dependency for building docker image

- modules/sfp_crt.py
- modules/sfp_fsecure_riddler.py
- modules/sfp_urlscan.py
Print number of domains pending DNS resolution.
Often, when modules produce a large number of results, a large number of domains are collected during initial parsing, which results in a lot of DNS queries. This PR prints a message so there's some visibility into how many domains are to be resolved.
> Print number of domains pending DNS resolution

- sfcli.py
`token = ""` is not a password.
`os.popen` is used by the `shell` CLI command to execute shell commands locally. This is expected.
```
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	running on Python 2.7.16
[node_visitor]	INFO	Unable to find qualified name for module: sfcli.py
Run started:2019-10-20 09:01:43.183268
Test results:
No issues identified.
Code scanned:
Total lines of code: 1036
Total lines skipped (#nosec): 2
Run metrics:
Total issues (by severity):
Undefined: 0
Low: 0
Medium: 0
High: 0
Total issues (by confidence):
Undefined: 0
Low: 0
Medium: 0
High: 0
Files skipped (0):
```
> Silence bandit warnings in sfcli

- requirements.txt
- sfwebui.py
https://secure.readthedocs.io/en/latest/frameworks.html#cherrypy
```
$ curl -isk http://127.0.0.1:5001 -X HEAD
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Server: CherryPy/18.3.0
Date: Sun, 17 Nov 2019 04:01:40 GMT
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
Pragma: no-cache
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Content-Length: 16657
```
> Use securepy - Fix #386

- sflib.py
```
test_dictnames_should_return_a_list (test.unit.test_spiderfoot.TestSpiderFoot) ... /root/Desktop/spiderfoot/test/unit/test_spiderfoot.py:399: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/Desktop/spiderfoot/dicts/ispell/names.dict' mode='r' encoding='UTF-8'>
dict_names = sf.dictnames()
```
```
/root/Desktop/spiderfoot/test/unit/test_spiderfoot.py:390: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/Desktop/spiderfoot/dicts/ispell/spanish.dict' mode='r' encoding='UTF-8'>
dict_words = sf.dictwords()
```
> Close files after read

- modules/sfp_dnsbrute.py
I haven't tested this, but I'm pretty sure for integer brute forcing for single digits, you want 0-9 not 0-8.
```
$ python
Python 2.7.17 (default, Oct 19 2019, 23:36:22) 
[GCC 9.2.1 20191008] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> for i in range(0, 9):
...   print(str(i))
... 
0
1
2
3
4
5
6
7
8
>>> for i in range(9):
...   print(str(i))
... 
0
1
2
3
4
5
6
7
8
>>> for i in range(10):
...   print(str(i))
... 
0
1
2
3
4
5
6
7
8
9
>>> 
```
```
$ python3
Python 3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> for i in range(0, 9):
...   print(str(i))
... 
0
1
2
3
4
5
6
7
8
>>> for i in range(9):
...   print(str(i))
... 
0
1
2
3
4
5
6
7
8
>>> for i in …
```
> Fix integer brute force

- dyn/scaninfo.tmpl
Not sure if these were overlooked, or if there's a reason for these tables to not be sortable.
The only downside I see is that the checkbox column looks silly sortable, and doesn't make much sense to be sortable.
> Allow event data and search results tables to be sortable

- test/unit/test_spiderfoot.py
Update Unit tests.
Current state of the tests:
```
____________________________________________________________________________ TestSpiderFoot.test_build_graph_data ____________________________________________________________________________
self = <test.unit.test_spiderfoot.TestSpiderFoot testMethod=test_build_graph_data>
def test_build_graph_data(self):
"""
Test buildGraphData(self, data, flt=list())
"""
sf = SpiderFoot(dict())
>       sf.buildGraphData(None)
test/unit/test_spiderfoot.py:102: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <sflib.SpiderFoot object at 0x7f8e909c9c90>, data = None, flt = []
def buildGraphData(self, data, …
```
> Update Unit Tests

- sfwebui.py
Use scan name for JSON export filename in the form of `<scan name>-SpiderFoot.json`.
It's probably vulnerable to HTTP header injection - depending on how well the user input is validated (the `cleanUserInput` function is insufficient).
> sfwebui: Use scan name for JSON export filename

- modules/sfp_crt.py
Add check for response content.
In the event of a connection error, without this check, the module would fail with a certificate parsing error. The cause of the error was not obvious, requiring reviewing the logs to determine that the response size was zero bytes.
> Add check for response content

- requirements.txt
Fixes #485
Note that this will break support for Python versions before 3.5.
> Peg CherryPy dependency to >=18.0

- sflib.py
Far from perfect.
```python
#!/usr/bin/env python3
import re
import html
content = "asdfhttp://zzz1234.asdf.zz.example.com:8080/1234/some/path?a=asdf>"
content += "<http://zzz5678.zxcv.zz.example.com:8080/5678/some/path/'%'?a=zxcv'%'''"
content += "<http://a@zzz9012.qewrty.zz.example.com:8080/9012/some/path?a=qwerty<"
print("Searching in: %s" % content)
print('...')
urls = re.findall("(https?://[a-zA-Z0-9-\.:]+/[\-\._~!\$&'\(\)\*\+\,\;=:@/%a-zA-Z0-9]*)", html.unescape(content))
for u in urls:
print(u)
```
```
$ ./urltest.py 
Searching in: asdfhttp://zzz1234.asdf.zz.example.com:8080/1234/some/path?a=asdf><http://zzz5678.zxcv.zz.example.com:8080/5678/some/path/'%'?a=zxcv'%'''<http://a@zzz9012.qewrty.zz.example.com:8080/9012/some/path?a=qwerty<
... …
```
> Add extractUrls function to extract all URLs from a string

- modules/sfp_dnsbrute.py
- modules/sfp_gravatar.py
- sflib.py
- sfwebui.py
* `assert` should not be used. Replaced `assert len(parent) == 2` with `if len(parent) != 2: return None`.
* `random.randint` was used for thread names which does require secure random. Replaced with `random.SystemRandom().randint`
* Use of MD5 was required for querying a remote service by md5 hash. Added `# nosec`.
* `0.0.0.0` was a false positive. This exists in a conditional statement which checks (not sets) the network interface. `0.0.0.0` is not the default network interface. Added `# nosec`.
> Silence bandit false positive warnings

- modules/sfp_multiproxy.py
- modules/sfp_watchguard.py
The missing commas are causing the produced event names to be concatenated.
> Add missing commas in producedEvents arrays

- sfdb.py
When running spiderfoot scans, I noticed issues with not being able to write log records and not being able to delete a stored scan while another one was running. This issue was aggravated by modules that spawn many threads (like sfp_accounts). Since sqlite doesn't allow multithreaded access, I've added a lock around the database-related code to prevent multiple threads from using the sqlite cursor at the same time. In a couple of places, I moved the commit invocation into the try/catch and protected section of code. (Note that most of the additions and deletions reported in the GitHub diff are whitespace differences. The actual changes are not that numerous.)
> Added locks to prevent multithread access to db

- sflib.py
- test/unit/test_spiderfoot.py
Validates input to `domainKeyword` and `domainKeywords` functions.
Changes `domainKeywords` out from `list()` to `set()`, thus removing duplicates. Also removes all `None` values from the returned `set()`.
> sflib: validate domainKeywords function input

- sf.py
- sfdb.py
- sflib.py
Added a dataPath method that queries a SPIDERFOOT_DATA environment variable for an optional override to where data files are stored. The default behavior is the same as before where all data and configs are stored in the sflib.myPath location. This change will allow Docker-based deployments to specify a Docker volume for data/config storage, allowing non-destructive container upgrades. #478
> Added support for configurable SpiderFoot data directory.

- sfwebui.py
I had noticed that a web UI rescan action was interpreting a user name as a human name while a clone action did not. This change fixed the issue.
> Fixed target type determination for webui rescan action

- sf.py
- sfwebui.py
The query route was having problems with utf-8 encoding of the results and was not able to JSON-encode a list with tuples. I changed the result to a list of dictionaries and enabled utf-8 encoding in CherryPy.
For the webui routes that invoke an action and then show a page for monitoring (rescan, etc.), I changed the behavior to invoke the action and then redirect to the monitoring page rather than rendering the target page in the handler. This helps to prevent accidental resubmission if the user refreshes the page and makes the monitoring page URL bookmark-friendly. 
I also corrected the pageid value for some of the template rendering functions.
> Fixed webui query route. Used redirects instead of rerender for some routes.

- test/unit/test_spiderfootplugin.py
The test was throwing an exception because the __sfdb__ class field (used in check_for_stop) was None. The test does a bit more than check for booleans now so I changed the name.
> Fix exception from check_for_stop unit test

- requirements_test.txt
Remove duplicated dependencies from `requirements_test.txt`.
The `netaddr` requirement was malformed.
```
$ pip3.7 install -r requirements_test.txt
...
ERROR: Invalid requirement: 'netaddr=0.7.19' (from line 7 of requirements_test.txt)
Hint: = is not a valid operator. Did you mean == ?
```
After fixing the formatting, it was revealed to be a duplicated dependency (as was `stem`), as per:
```
$ pip3.7 install -r requirements_test.txt
...
ERROR: Double requirement given: stem==1.8.0 (from -r requirements_test.txt (line 7)) (already in stem>=1.7.1 (from -r requirements.txt (line 16)), name='stem')
...
ERROR: Double requirement given: netaddr==0.7.19 (from -r requirements_test.txt (line 7)) (already in netaddr>=0.7.18 (from -r requirements.txt (line 8)), name='netaddr')
```
> Remove duplicated test dependencies

- sflib.py
Ensure `resolveTargets()` always returns a list. Rather than return `None` upon failure, an empty `list()` is returned instead.
The `resolveTargets` function is only used in one location - the sfp_dnsresolve module. An empty `list()` is effectively the same as `None` (ie, `False`), so this change should not affect the existing validation in use in this module:
```python
ret = self.sf.resolveTargets(target, self.opts['validatereverse'])
if not ret:
return target
```
> sflib: Ensure resolveTargets always returns a list

- sflib.py
Ideally this function should handle certificates more gracefully. Optionally, perhaps this function should return a `dict()` with `CertError = True` in the event of failure. This function is already kind of a mess and performs very little validation. For now, this change will act as early warning for invalid use of this function.
> sflib: Ensure parseCert function returns None if provided certificate is invalid

- sflib.py
Fixes test:
```
======================================================================
ERROR: test_resolve_ip_invalid_ip_should_return_none (test_spiderfoot.TestSpiderFoot)
Test resolveIP(self, ipaddr)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/root/Desktop/spiderfoot/test/unit/test_spiderfoot.py", line 670, in test_resolve_ip_invalid_ip_should_return_none
addrs = sf.resolveIP(None)
File "/root/Desktop/spiderfoot/sflib.py", line 1335, in resolveIP
self.debug("Performing reverse-resolve of " + ipaddr)
TypeError: can only concatenate str (not "NoneType") to str
```
> sflib: Ensure resolveHost/resolveIP function input is not None

- sflib.py
Resolves `test_target_type_invalid_seed_should_return_none ` failing test.
Check for `None` prevents:
```
______________________________________________________________ TestSpiderFoot.test_target_type_invalid_seed_should_return_none _______________________________________________________________
self = <test.unit.test_spiderfoot.TestSpiderFoot testMethod=test_target_type_invalid_seed_should_return_none>
def test_target_type_invalid_seed_should_return_none(self):
"""
Test targetType(self, target)
"""
sf = SpiderFoot(dict())
>       target_type = sf.targetType(None)
test/unit/test_spiderfoot.py:331: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> sflib: Ensure targetType target param is not empty

- sflib.py
Resolve failing `test_normalize_dns_should_return_list` test.
```
____________________________________________________________________ TestSpiderFoot.test_normalize_dns_should_return_list ____________________________________________________________________
self = <test.unit.test_spiderfoot.TestSpiderFoot testMethod=test_normalize_dns_should_return_list>
def test_normalize_dns_should_return_list(self):
"""
Test normalizeDNS(self, res)
"""
sf = SpiderFoot(self.default_options)
>       dns = sf.normalizeDNS(None)
test/unit/test_spiderfoot.py:566: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <sflib.SpiderFoot object at 0x7f8f667676d0>, res = …
```
> sflib: Ensure normalizeDNS returns a list

- sflib.py
Resolves failing `test_parse_emails_invalid_data_should_return_list` test.
```
______________________________________________________________ TestSpiderFoot.test_parse_emails_invalid_data_should_return_list ______________________________________________________________
self = <test.unit.test_spiderfoot.TestSpiderFoot testMethod=test_parse_emails_invalid_data_should_return_list>
def test_parse_emails_invalid_data_should_return_list(self):
"""
Test parseEmails(self, data)
"""
sf = SpiderFoot(self.default_options)
>       parse_emails = sf.parseEmails(None)
test/unit/test_spiderfoot.py:759: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> sflib: Ensure parseEmails returns a list

- sflib.py
- test/unit/test_spiderfoot.py
Resolves `test_parse_robots_txt_should_return_list ` failing test.
```
__________________________________________________________________ TestSpiderFoot.test_parse_robots_txt_should_return_list ___________________________________________________________________
self = <test.unit.test_spiderfoot.TestSpiderFoot testMethod=test_parse_robots_txt_should_return_list>
def test_parse_robots_txt_should_return_list(self):
"""
Test parseRobotsTxt(self, robotsTxtData)
"""
sf = SpiderFoot(self.default_options)
>       robots_txt = sf.parseRobotsTxt(None)
test/unit/test_spiderfoot.py:725: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <sflib.SpiderFoot …
```
> sflib: Ensure parseRobotsTxt returns a list

- sflib.py
This eliminates most of the deprecation warnings in `sflib`. The modules still need to be reviewed.
```
sflib.py:759
/root/Desktop/spiderfoot/sflib.py:759: DeprecationWarning: invalid escape sequence \d
{"^\d+\.\d+\.\d+\.\d+$": "IP_ADDRESS"},
sflib.py:760
/root/Desktop/spiderfoot/sflib.py:760: DeprecationWarning: invalid escape sequence \d
{"^\d+\.\d+\.\d+\.\d+/\d+$": "NETBLOCK_OWNER"},
sflib.py:762
/root/Desktop/spiderfoot/sflib.py:762: DeprecationWarning: invalid escape sequence \+
{"^\+\d+$": "PHONE_NUMBER"},
sflib.py:763
/root/Desktop/spiderfoot/sflib.py:763: DeprecationWarning: invalid escape sequence \s
{"^\".+\s+.+\"$": "HUMAN_NAME"},
sflib.py:765
/root/Desktop/spiderfoot/sflib.py:765: DeprecationWarning: invalid escape sequence \d
{"^\d+$": "BGP_AS_OWNER"},
sflib.py:767 …
```
> sflib: define regex strings as raw strings

- sflib.py
- test/unit/test_spiderfoot.py
Ideally this would check the database handle is a valid `SpiderFootDb` object (rather than simply checking `if not`) and `setDbh` would also ensure the provided database handle is a valid `SpiderFootDb` object when setting `self.dbh` in the first place; however, that would require importing `SpiderFootDb` into `sflib` which is not possible currently due to circular dependencies.
> sflib: Ensure _dblog without database handle raises exception

- sflib.py
- test/unit/test_spiderfoot.py
Ensure `resolveIP`, `resolveHost`, `resolveHost6` functions return a list.
An empty `list` is effectively `False`, so instances where these functions are used should be unaffected. I took a look through the modules and libs, and only a couple of updates were required:
```diff
-        if addrs is None:
+        if not addrs:
```
```diff
-        if self.resolveHost(randhost + "." + target) is None:
+        if not self.resolveHost(randhost + "." + target):
```
> sflib: Ensure resolveIP/resolveHost functions return a list

- requirements_test.txt
Required by `./test/test_pep8.py` for code style tests
> Add pycodestyle to test requirements

- test/unit/test_spiderfoot.py
Prevent generating the following warnings in unit tests:
```
test/unit/test_spiderfoot.py::TestSpiderFoot::test_parse_links_invalid_domains_should_return_a_dict
test/unit/test_spiderfoot.py::TestSpiderFoot::test_parse_links_invalid_url_should_return_a_dict
test/unit/test_spiderfoot.py::TestSpiderFoot::test_parse_links_should_return_a_dict
/usr/lib/python3/dist-packages/bs4/__init__.py:329: MarkupResemblesLocatorWarning: "data" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
warnings.warn(
```
> Prevent irrelevant Beautiful Soup warnings

- sfdb.py
Required for an upcoming PR related to subdomain takeovers.
> sfdb: Add AFFILIATE_INTERNET_NAME_HIJACKABLE data type

- modules/sfp_subdomain_takeover.py
Add `sfp_subdomain_takeover`, a rudimentary subdomain takeover scanner to check if affiliated subdomains (`AFFILIATE_INTERNET_NAME` / `AFFILIATE_INTERNET_NAME_UNRESOLVED`) are vulnerable to takeover, using the [fingerprints.json list by from subjack by haccer](https://github.com/haccer/subjack/master/fingerprints.json).
Requires #593 for `AFFILIATE_INTERNET_NAME_HIJACKABLE` data type.
Requires #595 for support for DNS CNAME records.
> Add sfp_subdomain_takeover

- sf.py
- sflib.py
- sfscan.py
- sfwebui.py
- test/unit/test_spiderfoot.py
- test/unit/test_spiderfootdb.py
- test/unit/test_spiderfootscanner.py
- test/unit/test_spiderfoottarget.py
- test/unit/test_spiderfootwebui.py
This should also fix #554 by ensuring scan IDs are automatically generated.
> sfscan: move startScan() functionality out of init()

- sflib.py
- test/unit/test_spiderfoot.py
Clean up `parseIBANNumbers` code; change expected length from `27` to `23` for `IL` country code; fix `parseIBANNumbers` tests.
> sflib: cleanup parseIBANNumbers function

- modules/sfp_dnsresolve.py
- sflib.py
- test/unit/test_spiderfoottarget.py
Use Python property decorators rather than setter/getter functions
for target type/value/aliases.
> SpiderFootTarget: use Python property decorators

- sfdb.py
- sfwebui.py
Validate result hash IDs in the `SpiderFootDb.scanElementSourcesDirect` and `SpiderFootDb.scanElementChildrenDirect`  functions.
This prevents blind SQL injection via the `/resultsetfp` route (and perhaps some others - whatever calls the aforementioned functions).
Proof of concept below. Note that the provided scan Id (`id` parameter) must be valid (for any scan).
```
curl 'http://127.0.0.1:5001/resultsetfp' --data-raw "id=5B9F4408&fp=1&resultids=%5B%229ea067b595f237c2eabff3653cda0c77eef786b6794e38a086b13dbf0463201a%22,%22') union select '1','2','3','4','5','6','7','8','9','10','11','12','13','14','15'%3b--a%22%5D"
```
> SpiderFootDb: validate result hash IDs

- sfdb.py
- sflib.py
- test/unit/test_spiderfootplugin.py
Fix #634 introduced in c3aaf63d0aee209c88df011655dc96c9509c3dac
> sflib: Ensure checkForStop() returns false when no scan ID is set

- sf.py
This isn't ideal, as the `[` is printed even when the scan fails due to an error.
Fix #636
> sf: Fix JSON output formatting when running sf from command line

- modules/sfp_pageinfo.py
Prevents returning URLs such as `https://` as externally hosted JS.
> sfp_pageinfo: ignore extenral JS URLs with no hostname

- dyn/scaninfo.tmpl
> sfwebui: modify scan info search button to pull right

- dyn/error.tmpl
- dyn/scandelete.tmpl
Make error page messages like this:
Look like this:
> sfwebui: change CSS class alert-error to alert-danger

- dyn/scaninfo.tmpl
> sfwebui: add scan status badge to scan info page heading

- sfcli.py
Prevents this error:
```
_________      .__    .___          ___________            __  
/   _____/_____ |__| __| _/__________\_   _____/___   _____/  |_ 
\_____  \\____ \|  |/ __ |/ __ \_  __ \    __)/  _ \ /  _ \   __\
/        \  |_> >  / /_/ \  ___/|  | \/     \(  <_> |  <_> )  |  
/_______  /   __/|__\____ |\___  >__|  \___  / \____/ \____/|__|  
\/|__|           \/    \/          \/                     
Open Source Intelligence Automation.
by Steve Micallef | @spiderfoot
Traceback (most recent call last):
File "./sfcli.py", line 1294, in <module>
s.dprint("Version " + s.version + ".")
File "./sfcli.py", line 127, in dprint
cout = col + bcolors.BOLD + pfx + " " + bcolors.ENDC + \
UnboundLocalError: local variable 'col' referenced before assignment
```
> sfcli: initialize col variable

- sfcli.py
Prevent `TypeError: object of type 'int' has no len()`:
```
_________      .__    .___          ___________            __  
/   _____/_____ |__| __| _/__________\_   _____/___   _____/  |_ 
\_____  \\____ \|  |/ __ |/ __ \_  __ \    __)/  _ \ /  _ \   __\
/        \  |_> >  / /_/ \  ___/|  | \/     \(  <_> |  <_> )  |  
/_______  /   __/|__\____ |\___  >__|  \___  / \____/ \____/|__|  
\/|__|           \/    \/          \/                     
Open Source Intelligence Automation.
by Steve Micallef | @spiderfoot
[*] Version 3.2-DEV.
[*] Server http://127.0.0.1:5001 responding.
[*] Loaded previous command history.
[*] Type 'help' or '?'.
sf> query "SELECT '1'"
'1'  
---
1
[*] Total records: 1
sf> query "SELECT 1"
Traceback (most recent call last):
File "./sfcli.py", line 1313, in <module> …
```
> sfcli: Cast dict value as string

- dyn/scaninfo.tmpl
Fix cell position alignment for `Data Element Type` column on scan info search results page to be consistent.
> sfweui: Use consistent formatting for data type column

- sfdb.py
- sflib.py
- test/unit/modules/test_sfp_bitcoin.py
- test/unit/modules/test_sfp_company.py
- test/unit/modules/test_sfp_countryname.py
- test/unit/modules/test_sfp_creditcard.py
- test/unit/modules/test_sfp_dnsresolve.py
- test/unit/modules/test_sfp_email.py
- test/unit/modules/test_sfp_errors.py
- test/unit/modules/test_sfp_ethereum.py
- test/unit/modules/test_sfp_hashes.py
- test/unit/modules/test_sfp_hosting.py
- test/unit/modules/test_sfp_iban.py
- test/unit/modules/test_sfp_names.py
- test/unit/modules/test_sfp_pageinfo.py
- test/unit/modules/test_sfp_phone.py
- test/unit/modules/test_sfp_strangeheaders.py
- test/unit/modules/test_sfp_webanalytics.py
- test/unit/modules/test_sfp_webframework.py
- test/unit/test_spiderfootdb.py
- test/unit/test_spiderfootevent.py
- test/unit/test_spiderfootplugin.py
This PR rewrites much of the `SpiderFootEvent` class to use `@property` and `@property.setter`.
All the validation logic has been moved out of the `init` function into the getters/setters. There are no setters for properties which should be private (ie, `self.generated`).
The `setConfidence` / `setVisibility` / `setRisk` functions have been removed. Appropriate getters and setters now exist for these properties.
The `sourceEventHash` property is now calculated automatically when the `sourceEvent` is set. It can no longer be set outside of the class, as there should never be a reason for the source event hash to be set manually. Changing the hash requires changing the `sourceEvent`.
The `getHash` function has been replaced with a `hash` property and can no longer be set outside the class, …
> sflib: SpiderFootEvent: Use attributes and setters

- requirements.txt
```
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| pyopenssl                  | 16.2.0    | <17.5.0                  | 36533    |
+==============================================================================+
| Python Cryptographic Authority pyopenssl version prior to version 17.5.0     |
| contains a CWE-416: Use After Free vulnerability in X509 object handling     |
| that can result in Use after free can lead to possible denial of service or  |
| remote code execution.. This attack appear to be exploitable via Depends on  |
| the calling application and if it retains a reference to the …
```
> requirements: Bump pyOpenSSL>=16.2.0 to pyOpenSSL>=17.5.0

- requirements.txt
[future](https://pypi.org/project/future/) is not used for Python 3. `future` is no imported anywhere.
> requirements: Remove 'future' dependency

- dyn/scaninfo.tmpl
Prevent endless refreshing every 5 seconds if the scan is complete (`ERROR-FAILED` `FINISHED` `ABORTED`)
> sfwebui: clear scan summary refresh interval when scan is complete

- .travis.yml
Given that pip now has a real dependency resolver it is better to give it all dependencies in one command.
> Travis CI: pip now has a real dependency resolver

- modules/sfp_hostio.py
Since sfp_countryname is responsible to pull country names out of GEOINFO, we should avoid this duplication.
> Remove COUNTRY_NAME event from hostio

- sf.py
- sfscan.py
Resolves #880
Allowing DNS resolution via the proxy would be a good option have. However, it should removed from now, as this is dead code that does nothing, and offering the option users is misleading.
> sf: remove '_socks6dns' config option

- sf.py
This config option is dead code that does nothing and offering the option to users is misleading.
> sf: Remove '_fatalerrors' config option

- modules/sfp_abuseipdb.py
Resolves #361
The failing test is unrelated to this change. Looks like an intermittently failing test. This test is new and may need to be disabled.
```
=================================== FAILURES ===================================
____________ TestSf.test_run_scan_should_print_scan_result_and_exit ____________
self = <test.unit.test_sf.TestSf testMethod=test_run_scan_should_print_scan_result_and_exit>
def test_run_scan_should_print_scan_result_and_exit(self):
target = "spiderfoot.net"
out, err, code = self.execute([sys.executable, "sf.py", "-m", ",".join(self.default_modules), "-s", target, "-o", "csv"])
self.assertIn(b"Scan completed with status FINISHED", err)
self.assertEqual(0, code)
for module in self.default_modules:
with self.subTest(module=module): …
```
> sfp_abuseipdb: Fix watched/produced events and timeout

- sf.py
Fix terminal output. Ensure scan output headings are printed before scan results.
> sf: fix terminal scan output headers

- modules/sfp_crossref.py
Ensuring the URL FQDN resolves should see a noticeable improvement in speed:
```python
if not self.sf.resolveHost(fqdn):
self.sf.debug(f"Ignoring {url} as {fqdn} does not resolve")
return None
```
> sfp_crossref: Ensure URL FQDN resolves; and code cleanup

- modules/sfp_viewdns.py
Also fixes a bug where `errorstate` was not set when the API key usage limit had been exceeded.
> sfp_viewdns: code cleanup

- modules/sfp_dnscommonsrv.py
Also removes this module from the `passive` use case and adds `slow` flag.
Also fixes a bug where each SRV record was reported multiple times.
> sfp_dnscommonsrv: code cleanup

- sf.py
Cherrypy already uses the existing configured log objects. No need to duplicate logs also to `stdout`.
> sfwebui: disable logging to screen

- modules/sfp_ipregistry.py
- modules/sfp_template.py
- modules/sfp_zetalytics.py
In modules where it can remain (at least for now), remove the unused `notify` flag.
> Remove emit() from the template

- sflib.py
Since ba0c2d18b7484e54e16c8fc65d7b2bcade33ffb2 debug messages were not logged in the database. This was a mistake. The same code pattern should have been used for the `debug` function as used for the `status` and `info` functions.
> sflib: log debug messages in database

- dyn/opts.tmpl
Each option field only has one form control, so there is no need to use `input-group`. Instead, `form-group` can be used. This PR also adds Bootstrap styling to `select` elements
> Use Bootstrap form-group instead of input-group

- modules/sfp_leakix.py
Hi, I'm adding this before tomorrow's deployment so it's ready just in case !
I'm not sure I should add `apikey` in `tags` since it won't be strictly required. The results will be limited in time if it's not present though.
Thanks for the orignal plugin @bcoles and the whole team for the tool :heart:
> sfp_leakix: Added api-key support

- requirements.txt
- sf.py
Does not support sending CORS request with credentials.
For now, a user must edit the source to whitelist an origin.
It does not make sense to wire this up to command line options. This can be resolved once SpiderFoot makes use of a config file for configuration options.
> sfwebui: Add support for CORS

- sfcli.py
There is a small typo in sfcli.py.
Should read `processing` rather than `proessing`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, proessing -> processing

- README.md
Apparently this was too confusing for users who aren't familiar with their terminal.
> README: Remove example shell prompt from "installing and running" steps

- Dockerfile
With the current `Dockerfile`, attempting to build the image from it using `docker build -t spiderfoot:latest .` results in the following (truncated) error.
```
...
copying src/cryptography/py.typed -> build/lib.linux-x86_64-3.6/cryptography
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.6/_padding.c'
creating build/temp.linux-x86_64-3.6
generating cffi module 'build/temp.linux-x86_64-3.6/_openssl.c'
running build_rust
=============================DEBUG ASSISTANCE=============================
If you are seeing a compilation error please try the following steps to
successfully install cryptography:
1) Upgrade to the latest pip and try again. This will fix errors for most
users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2) Read …
```
> Upgrade pip to prevent issues with building Cryptography Python package

- spiderfoot/__version__.py
To be used when packaged as a pip package.
> spiderfoot: Add __version__.py

- .travis.yml
- requirements_test.txt
I've been using `pytest-xdist` locally for over a year to significantly speed up tests.
I forget if there was a reason we weren't already using this in `requirements_test.txt` for CI. Let's see if the tests pass.
> requirements_test: Add pytest-xdist==2.2.1

- test/unit/modules/test_sfp_reversewhois.py
This test does not make sense and should be skipped.
> Tests: test_sfp_reversewhois: skip invalid test

- spiderfoot/db.py
Used for a work-in-progress module. LEI (Legal Entity Identifier) allows uniquely identifying organisations which assists with matching and normalisation of companies.
> DB: Add 'LEI' (Legal Entity Identifier) data type

- modules/sfp_reversewhois.py
Resolves this warning:
```
/root/Desktop/spiderfoot/modules/sfp_reversewhois.py:78: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
The code that caused this warning is on line 78 of the file /root/Desktop/spiderfoot/modules/sfp_reversewhois.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.
html = BeautifulSoup(res["content"])
```
> sfp_reversewhois: Use lxml parser for BeautifulSoup

- requirements_test.txt
Version 6.2.4 fixes some bugs and security issues.
> requirements: Bump pytest version from 6.0.2 to 6.2.4

- modules/sfp_names.py
- test/unit/modules/test_sfp_names.py
The number checking was broken causing names to not be reported.
Added tests to prove that the new method works correctly.
> sfp_names: Fix HUMAN_NAME extraction from email addresses

- sfscan.py
- spiderfoot/plugin.py
* **No functionality was deleted, and there are no changes to individual modules.** A non-threaded scan can still be invoked by passing `threaded=False` to `SpiderFootScanner.__startScan()`
* When threading is enabled, each module gets its own dedicated queue for "incoming" events, and shares an "outgoing" queue to `SpiderFootScanner`, which distributes new events across all the modules.
* A status message periodically shows which modules have the most events queued. This makes it easy to identify slow-performing modules which are bottlenecking the scan.
```
[INFO] sfscan : Events queued: sfp_sslcert: 595, sfp_mnemonic: 569, sfp_pgp: 472, sfp_dnscommonsrv: 400, sfp_fringeproject: 357
```
> Feature: Threaded Modules

- sfcli.py
- test/unit/test_spiderfootcli.py
Allows users to set options with a connection to a server. Useful for setting `history`, `spool`, `debug`, etc.
Also makes a bunch of style changes (return-early and no-else-after-return).
> sfcli: Allow setting local options without a server connection

- sf.py
- sfwebui.py
- spiderfoot/helpers.py
- test/unit/test_spiderfoothelpers.py
This was too confusing as we have various accessors and paramaters elsewhere called targetType.
> SpiderFootHelpers: rename SpiderFootHelpers.targetType to SpiderFootHelpers.targetTypeFromString

- modules/sfp_dnsresolve.py
This was resolved in 89b7633608c909013b49ee32c987ce935a6bd0fc but the `TODO` comment was not removed.
> sfp_dnsresolve: Remove stale TODO comment

- requirements.txt
- spiderfoot/helpers.py
The following error was introduced recently, seemingly the result of a change in the `networkx` library. It is resolved by modifying the import statement to `import networkx as nx`.
```
spiderfoot    | Traceback (most recent call last):
spiderfoot    |   File "sf.py", line 31, in <module>
spiderfoot    |     from sfscan import SpiderFootScanner
spiderfoot    |   File "/home/spiderfoot/sfscan.py", line 24, in <module>
spiderfoot    |     from spiderfoot import SpiderFootDb, SpiderFootEvent, SpiderFootPlugin, SpiderFootTarget, SpiderFootHelpers
spiderfoot    |   File "/home/spiderfoot/spiderfoot/__init__.py", line 5, in <module>
spiderfoot    |     from .helpers import SpiderFootHelpers
spiderfoot    |   File "/home/spiderfoot/spiderfoot/helpers.py", line 5, in <module>
spiderfoot    | …
```
> Resolve networkx import error

- requirements.txt
Unfortunately `ipwhois` 1.2.x is not compatible with `dnspython` 2.x.
> requirements: Lock ipwhois dependency to >=1.1.0,<1.2.0

- modules/sfp_searchcode.py
I'm not sure if the API previously started at page one or if this is a bug which has always existed in this module.
> sfp_searchcode: Start from page 0 not page 1

- modules/sfp_dnsdumpster.py
They updated the the page to require an extra POST parameter: `user=free`.
> DNSDumpster Fix

- spiderfoot/templates/opts.tmpl
Adds changes to `opts.tmpl` template missed in #1264.
> sfwebui: do not show api key instructions for modules with no instructions

- modules/sfp_tool_cmseek.py
If `CMSeek` has never been run before, the `Result` directory will not exist, and `CMSeek` will hang waiting for user input to confirm proceeding.
Running `CMSeek` with the `--batch` flag ensures the directory is created automatically (presuming sufficient privileges to create the directory).
> sfp_tool_cmseek: Run CMSeek in --batch mode

- test/unit/test_spiderfoot_module_loading.py
This test can be enabled now that #1266 has been resolved.
> Tests: Enable test_modules_with_api_key_have_apiKeyInstructions test

- modules/sfp_blocklistde.py
> sfp_blocklistde: Set correct timeout argument for self.sf.fetchUrl()

- modules/sfp_abusech.py
- modules/sfp_bambenek.py
- modules/sfp_bitcoin.py
- modules/sfp_cinsscore.py
- modules/sfp_circllu.py
- modules/sfp_cleantalk.py
- modules/sfp_coinblocker.py
- modules/sfp_company.py
- modules/sfp_customfeed.py
- modules/sfp_dnsraw.py
- modules/sfp_emailcrawlr.py
- modules/sfp_emergingthreats.py
- modules/sfp_greensnow.py
- modules/sfp_hunter.py
- modules/sfp_hybrid_analysis.py
- modules/sfp_jsonwhoiscom.py
- modules/sfp_malwaredomainlist.py
- modules/sfp_onyphe.py
- modules/sfp_pageinfo.py
- modules/sfp_pastebin.py
- modules/sfp_subdomain_takeover.py
- modules/sfp_tool_nmap.py
- modules/sfp_zetalytics.py
- setup.cfg
Note: A couple of modules were overriding the `id` builtin. These modules also need to be rewritten. `id` has been replaced with `replaceme_id` as a temporary measure.
> flake8: modules: Resolve violations: A, SFS101, SFS201

- test/acceptance/run
- test/bandit
- test/run
- test/update-requirements
Adds a few scripts I use locally. I use these often enough for testing that they may be useful to keep in the repo.
`test/run` is a simple wrapper for the unit and integration tests. When testing local changes, if these tests complete successfully, then the tests should also pass upon pull request when run as part of the GitHub tests workflow.
`test/acceptance/run` is a simple wrapper to run the acceptance tests.
`test/update-requirements` may be useful to update dependencies before a release, to ensure SpiderFoot works with the latest versions
`test/bandit` already existed in tree, but needed to be updated to account for the new `./spiderfoot` directory. This script wraps `bandit` to find security issues with static analysis. For now, we're using this separately rather than as part of …
> Tests: Add a few simple test wrapper shell scripts

- modules/sfp_phishtank.py
This module was erroneously returning a match regardless of whether the target was in the blacklist resulting in false positives.
> sfp_phishtank: Fix blacklist host check

- sf.py
- sflib.py
- sfscan.py
- sfwebui.py
- spiderfoot/logger.py
- spiderfoot/plugin.py
- test/unit/test_spiderfoot.py
This PR creates a logging handler for SQLite and consolidates all logging activity into its own thread. This is accomplished with Python's built-in classes `logging.handlers.QueueHandler` and `logging.handlers.QueueListener`.
Provided it is properly initialized, **logging can now be performed anywhere without worrying about database locks, processes, or threads**:
```python
import logging
log = logging.getLogger(f"spiderfoot.{__name__}")
log.info("test")
```
This PR is adapted directly from the official multiprocessing example in [Python Logging Cookbook](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes).
Logging code resides in a new file, `spiderfoot/logger.py`, which exposes functions for initializing logging in SpiderFoot.
When the …
> Unify logging with QueueHandler

- spiderfoot/event.py
- test/unit/spiderfoot/test_spiderfootevent.py
We've never used these. They are always set to default.
Other properties that we do actually use, like `actualSource`, are set directly. ie, `event.actualySource = '...'`. We can do the same with risk/visibility/confidence if necessary.
> spiderfoot: event: Remove risk/visibility/confidence args from constructor

- sf.py
- sflib.py
- spiderfoot/helpers.py
- test/conftest.py
- test/integration/test_sfwebui.py
- test/run
- test/unit/test_spiderfoot.py
This change is important.
It may lead to some initial confusion for anyone using the `master` branch. Short term pain for long term gain.
Your data is fine. Your data in `spiderfoot.db` is fine. It is still there.
The application is loading data from `$HOME/.spiderfoot/spiderfoot.db` now. (or `$SPIDERFOOT_DATA/spiderfoot.db` if you have the environment variable set.)
You can copy/move your old database from `/path/to/spiderfoot/spiderfoot.db` to `$HOME/.spiderfoot/spiderfoot.db` to restore all settings and scans.
> spiderfoot: store data and cache in user's home directory

- Dockerfile
- Dockerfile.full
- docker-compose.yml
- spiderfoot/db.py
Fixes in `Dockerfile.full` and updates to `docker-compose.yml` to accommodate the new data location.
> Docker updates, fixes

- sfscan.py
- spiderfoot/plugin.py
This PR adds a shutdown hook so that (future) modules that support concurrent/batch processing of events can wrap up their operations cleanly.
> Add Module Shutdown Hook

- spiderfoot/target.py
This wires up the `SpiderFootTarget` class to (eventually) support IPv6 netblocks as a valid target type.
Note: Scans can not yet be run on IPv6 netblocks (both before and after this PR).
All modules which watch and produce `NETBLOCK*` events need to be reviewed and updated to handle the new `NETBLOCKV6_OWNER` data type appropriately.
Once this is ready, the `SpiderFootHelpers.targetTypeFromString` function can be updated to support IPv6 netblocks as input for new scans.
> SpiderFootTarget: Add NETBLOCKV6_OWNER as a valid target type

- spiderfoot/helpers.py
Updates the `SpiderFootHelpers.targetTypeFromString` function to support IPv6 netblocks as input for new scans.
This isn't advertised anywhere in the user interface yet. Many modules which accept `NETBLOCK*` events still need to be reviewed for IPv6 handling.
I need this change locally for testing and it needed to be made eventually anyway.
> SpiderFootHelpers: targetTypeFromString: Add NETBLOCKV6_OWNER target type

- sfscan.py
- spiderfoot/plugin.py
- test/unit/spiderfoot/test_spiderfootplugin.py
A spiderfoot-integrated threading pool
Each thread in the pool is spawned only once, and reused for best performance.
```python
with self.threadPool(self.opts["_maxthreads"]) as pool:
for result in pool.map(
callback,
["a", "b", "c", "d"],
args=("arg1",)
kwargs={kwarg1: "kwarg1"}
):
yield result
with self.threadPool(self.opts["_maxthreads"]) as pool:
pool.start(callback, "arg1", kwarg1="kwarg1")
pool.submit(a)
pool.submit(b)
for result in pool.shutdown():
yield result
```
> Added spiderfoot-integrated thread pool

- modules/sfp_accounts.py
`50` threads is a bit high for a module which makes HTTP requests.
By default, modules which make HTTP requests have `maxthreads` set to 20 (at most).
By default, modules which make DNS requests have `maxthreads` set to 50 (or 100).
> sfp_accounts: Change maxthreads default from 50 to 20

- sfwebui.py
Untested but seems reasonable.
Fixes #1458
The database is initialized in `start_scan` in `sf.py` but not in `start_web_server`.
> sfwebui: Initialize database at web server startup

- modules/sfp_spyse.py
Significant rewrite of `sfp_spyse`. Also adds support for `IPV6_ADDRESS` events.
This squashes a lot of bugs caused by the Spyse API updates from version 1 to version 4.
See also:
* #526
* #527
* #1237
> sfp_spyse: Cleanup and add support for IPv6 addresses

- modules/sfp_coinblocker.py
Cleans up the `sfp_coinblocker` module code style.
Also modifies the module to watch only `INTERNET_NAME` related events (including affiliates and cohosts) not `IP_ADDRESS` related events.
Also removes the `https://zerodot1.gitlab.io/CoinBlockerLists/MiningServerIPList.txt` file as a data source. This file has been missing for a long time.
Searching back through the git commit history shows the file didn't exist as far  back as April 2019 (over 2 years ago) and perhaps a lot longer.
All the lists on the [downloads page](https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html) are for domain names, not IP addresses. There's one list for IP addresses ("Bad IPs Feed"), but this list is not freely available for download.
> sfp_coinblocker: Cleanup and remove URL for missing MiningServerIPList.txt file

- sf.py
- spiderfoot/helpers.py
- test/conftest.py
- test/integration/test_sfwebui.py
- test/unit/test_modules.py
This has been on the todo list for a long time. Consolidates the module loading, parsing and sanity checking into one helper function.
> Move module loading to SpiderFootHelpers.loadModulesAsDict() function

- modules/sfp_tool_nuclei.py
- modules/sfp_tool_retirejs.py
- modules/sfp_tool_wappalyzer.py
This makes them grepable.
Helping users on GitHub and Discord has required grepping modules on dozens of occasions.
> Modules: Keep module meta useCases array items on single line

- modules/sfp_stackoverflow.py
- test/unit/modules/test_sfp_stackoverflow.py
This fixes a design flaw in the `sfp_stackoverflow` module. The module tries to setup the `sfp_names` module and force it to handle an event. This goes against the SpiderFoot architecture. This is also unnecessary if the `sfp_names` module was included in the scan. If this was any other module it would usually be a minor inconvenience. Unfortunately, the `sfp_names` module loads multiple dictionaries during startup, resulting in a `list` of almost 900 thousand entries every time the module encountered a username. This causes issues on systems with ~2GB RAM or less.
Also reports IP addresses as affiliates `AFFILIATE_IPADDR` / `AFFILIATE_IPV6_ADDRESS` rathar then `IP_ADDRESS` / `IPV6_ADDRESS`.
> sfp_stackoverflow: Cleanup and add tests

- .github/workflows/tests.yaml
Eventually I'll move module integration tests to the `test/integration/modules/ directory.
This change lets us keep module integration tests in the repository, but skips running them on CI. These tests are often temperamental and rely on third-parties which may be down temporarily when the tests run. They may also not appreciate receiving six queries every time the CI tests run (3 versions of Python * 2 OS).
> Tests: Ignore module integration tests on CI

- modules/sfp_dnsbrute.py
Another step towards removing `SpiderFoot.myPath()` and packaging SpiderFoot as a package.
> sfp_dnsbrute: importlib.resources.open_text to load dictionaries

- sfwebui.py
- spiderfoot/db.py
Fixes #310
The `vacuumDB()` function is accessible via an undocumented `/vacuum` URL route.
> SpiderFootDb: Add vacuumDB() function to clear unused database file pages

- modules/sfp_spider.py
This significantly decreases complexity and significantly improves readability of the `spiderFrom()` function while retaining the same behaviour. Also significantly decreases the function length.
Fixes #1688 - a bug where sfp_spider would assume `fetchUrl()` cannot return `None`.
Also patches a bug where the `data` argument to `extractLinksFromHtml()` could be passed as `bytes` instead of a UTF-8 encoded `str`.
Also likely patches a bug in a call to `fetchUrl()` with a superfluous `False` argument.
> sfp_spider: Reduce complexity of spiderFrom function

- sflib.py
- sfscan.py
Now that we use a native `logger` we can ditch `traceback.format_exc`.
This makes the "Please report this as a bug: ..." output easier to read.
> Logging: Use exc_info=True rather than printing traceback.format_exc

- modules/sfp_alienvault.py
- modules/sfp_fraudguard.py
- modules/sfp_pulsedive.py
- modules/sfp_robtex.py
In some modules `max_netblock` is defined then subsequently overwritten with a potentially invalid value.
> Modules: Fix maxnetblock size check in several modules

- modules/sfp_threatjammer.py
<p align="center">
</p>
[ThreatJammer.com](https://threatjammer.com/) is a service that allows developers, security engineers, and other IT professionals to access high-quality threat intelligence data from a variety of sources and integrate it into their applications with the sole purpose of detecting and blocking malicious activity.
The assessment endpoint of the API returns a risk score with the estimated probability of being a malicious IP address. Less than 35 means Low risk, and more than 67 means High risk. This is the API endpoint used in the module for IPv4 and IPv6 addresses for the BLACKLISTED_IPADDR and MALICIOUS_IPADDR events.
Anybody can sign up and use the service for free forever. 
To use the module the user must [sign up and obtain an API …
> Threat Jammer module for blacklist/malicious IP

- README.md
Hence just to make it little more convenient for the users , please merge my pull request :).
> Made copying and pasting from the README.md to terminal easier.

- sflib.py
NIST CVE data parsing for CVE score and description skipping a layer in the dictionary resulting in an exception for all queried CVEs.
> bugfix for nist cve data parsing

- modules/sfp_fsecure_riddler.py
[F-Secure Riddler](https://riddler.io/) has been having intermittent issues since late 2022, sometimes returning a HTTP 500 error:
* http://web.archive.org/web/20221224052214/https://riddler.io/
At time of writing it is currently returning a HTTP 500 error for both the landing page and the API.
This PR fixes a bug where login failure was not checked correctly, causing the module to continue to run without a valid login token.
This was particularly problematic, as this caused the module to attempt to login every time the module received an event. Worse, this module contains a one second sleep in the `query` function. As such, every watched event was generating a login HTTP request, and a query HTTP request which was doomed to failure, followed by a one second delay.
```
2023-02-18 …
```
> sfp_fsecure_riddler: Check for login failure

- .github/workflows/tests.yaml
- test/requirements.txt
- test/run
Python 3.10 has been around for a while and is the default Python version on Kali Linux.
Python 3.7 is end of life in about 3 months (June 2023).
https://devguide.python.org/versions/
---
We already do this (since #1203) for GitHub workflows. It makes sense to also do this locally.
This allows the lint tests to fail first which speeds up the local test workflow in the event of failure.
Invoking `flake8` directly instead of via `pytest` allows us to remove `pytest-flake8` from the test requirements, which allows us to clean up the requirements a bit.
`pytest-flake8` is not compatible with newer versions of `flake8`, so we had to pin `flake8` to an old version.
This PR removes `pytest-flake8` and updates `pycodestyle` to `2.9.0` and `flake8` to `5.0.4`. These are the latest versions which …
> Tests: Run flake8 lint test before pytest

- sf.py
> sf: allow 60 seconds for post-scan correlations to complete
